module.exports = {
  apps: [
    {
      name: "cfi-backend-prod",
      cwd: "C:/Users/etejeda/Desktop/Proyectos/CFI/CFI_BACKEND",
      script: "C:/Users/etejeda/Desktop/Proyectos/CFI/CFI_BACKEND/venv/Scripts/python.exe",
      args: [
        "-m",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ],
      interpreter: "none",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: "5s",
      restart_delay: 2000,
      windowsHide: true,
      out_file: "C:/Users/etejeda/Desktop/Proyectos/CFI/CFI_BACKEND/logs/pm2-backend-out.log",
      error_file: "C:/Users/etejeda/Desktop/Proyectos/CFI/CFI_BACKEND/logs/pm2-backend-error.log",
      env: {
        APP_ENV: "production",
      },
    },
    {
      name: "cfi-frontend-prod",
      cwd: "C:/Users/etejeda/Desktop/Proyectos/CFI/CFI_FRONTEND",
      script: "C:/Program Files/nodejs/node.exe",
      args: [
        "node_modules/vite/bin/vite.js",
        "preview",
        "--host",
        "0.0.0.0",
        "--port",
        "5173",
        "--strictPort",
      ],
      interpreter: "none",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: "5s",
      restart_delay: 2000,
      windowsHide: true,
      out_file: "C:/Users/etejeda/Desktop/Proyectos/CFI/CFI_BACKEND/logs/pm2-frontend-out.log",
      error_file: "C:/Users/etejeda/Desktop/Proyectos/CFI/CFI_BACKEND/logs/pm2-frontend-error.log",
      env: {
        NODE_ENV: "production",
      },
    },
  ],
};
